### PR TITLE
EVENT-506: Refactor default answer values in blockRegistraion

### PR DESCRIPTION
**Pull request by OzzieOrca**
https://jira.cru.org/browse/EVENT-506

### CODE REVIEW

**Comment by OzzieOrca** [comment]
Haha ya this code is a mess. Thanks for looking through it/testing it. None of it has tests written for it and I feel like I'm going to break something and not know it... I think some of the logic should be refactored into the block types they belong with. It would be nice to refactor some of the block logic into Angular 1.5 components and get some of the logic out of the shared `$scope`. Lee wanted me to make a Jira task for some of this refactoring.

**Comment by OzzieOrca** [comment]
For some reason the tests for the date filter kept failing on Travis only. The code seemed to not cover all the days. Idk. I cleaned it up with some of moment's newer api methods.

@dougworner Could you review that and approve this PR?

**Comment by OzzieOrca** [comment]
I decided to just merge this since it's a bug in production. Let me know if you see anything wrong in it.

**Comment by dougworner** [comment]
@OzzieOrca Sorry I was in bed when you sent the request to review.

**Comment by dougworner** [comment]
@OzzieOrca I tested all selecting in date filter on landing page and worked successfully.  See you added test cases too.  Curious why you made this change with this pull request that is related to a Jira event for a different issue. Was this something you just noticed and wanted to make the change quickly?

**Comment by dougworner** [comment]
@OzzieOrca Ah...never mind noticed your comment above about this being a bug in production.  Yah.  That would need to fixed quickly.  👍

**Comment by OzzieOrca** [comment]
Ya sorry. The date filter test kept failing on Travis so it wouldn't let me deploy it without fixing that. I think it was dependent on the day of the week.

**Pull request merged**
