### PR TITLE
Pull request for Event-428 Changes

### PR DESCRIPTION
**Pull request by dougworner**
Add ability to show/hide display columns

### CODE REVIEW

**Comment by dougworner** [comment]
Lee, I had to remove the pull request and create a new one.  After doing some research on the Travis error it appears be something that is known by Github but no workaround exists yet.

**Comment by hlbraddock** [comment]
I'm a little confused at this point. The only commit I see in this PR is entitled 'merging in master'. 

Are the changes in this PR the changes you made for adding ability to hide columns or just an update from the master branch?

@dougworner

**Comment by hlbraddock** [comment]
It looks like in fact these are the changes as per https://jira.cru.org/browse/EVENT-428 requirements, namely:

'On the list of registrations conference admin page, Unlock "Started," "Completed" and "Email" display columns to allow admin to remove from display screen (leaving the "First Name," "Last Name," "Registrant Type" and "Paid" locked).'

However, the commit message is not reflective of this.

**Comment by hlbraddock** [comment]
So, it looks like you made a new branch from master and made one commit to introduce your changes.

**Comment by dougworner** [comment]
That is correct.  I had to because of the Travis error was preventing a successful build.  I amended the last commit message to reflect what you wrote.

**Comment by OzzieOrca** [comment]
It looks like in the merge, a bunch of the `translate` tags and directives got removed. I think Adam added those recently so they weren't on master when you started but probably created merge conflicts when you rebased your branch on master.

Once those are back 👍

**Comment by dougworner** [comment]
Hey Scotty,
Not sure if I'm following.  You'll have to bear with me as this is my first experience using Github on this change request.  Is there still something you need for me to do?

**Comment by hlbraddock** [comment]
What I might recommend is creating a completely new branch from master, add your changes in one commit, and submit a new PR.

If it's too difficult to capture all your changes in another branch, then you can disregard this suggestion.

**Comment by OzzieOrca** [comment]
Ya if you click the [files changed tab](https://github.com/CruGlobal/conf-registration-web/pull/477/files) above this conversation, you'll notice that master (highlighted in red) had a bunch of `<translate>` and `translate` tags. They were removed with you changes (highlighted in green) probably in resolving a merge conflict.

**Pull request closed without merging**
