### PR TITLE
discount to registration

### PR DESCRIPTION
**Pull request by adammeyer**

### CODE REVIEW

**Comment by adammeyer** [comment]
@ryancarlson Can you review?  This adds the ability for an admin to add a discount.

**Comment by ryancarlson** [comment]
I don't think the API is setup to recognize 'DISCOUNT' as a type, is it, @mattfred ?

**Comment by adammeyer** [comment]
Correct.  It's saving it as Additional Expense.

**Comment by ryancarlson** [comment]
Got it.  The transaction type is what threw me off.  I thought the API was tracking that, but I checked the code and see that it's not.

**Comment by ryancarlson** [comment]
This looks good.  Please test it on stage and verify there before deploying to production.

Also, I would like the API to change the name of the database table and entity and endpoint to be `adjustment` instead of `expense` soon.  The client should update the path it uses too when the API changes. This doesn't have to happen right away, but just so we don't forget about it.

**Pull request merged**
