### PR TITLE
EVENT-660 - Blurb for International Currency Selection

### PR DESCRIPTION
**Pull request by caleballdrin**
Added Disclaimer "?" blurb for International Currency Selection

### CODE REVIEW

**Comment by wrandall22** [comment]
So, you should look into yarn, and how it works with lint. That should get the Travis build running correctly. Also, you can use yarn to run the project locally to test your change. You can take a screenshot and post it here in the comments.

**Comment by TheNoodleMoose** [comment]
@caleballdrin Yeah to jump onto what @wrandall22 said, the build is failing because we use something called prettier to format the code. If you are using VSCode, you can install the prettier plugin and it will format on save for you(you have to change the settings to do this). If not once you get the project running locally, you can run `yarn prettier:write` and it will format the whole project and fix the error.

**Comment by wrandall22** [comment]
Another thing that would be nice (for convenience and convention) would be to put a link to the Jira ticket in the PR description.

**Comment by caleballdrin** [comment]
I want to merge into staging not master.

**Pull request closed without merging**
