### PR TITLE
EVENT-798 - Add chartfield to promotions

### PR DESCRIPTION
**Pull request by wrandall22**
[Jira](https://jira.cru.org/browse/EVENT-798) and associated https://github.com/CruGlobal/ert-api/pull/994.

This PR adds chartfield text fields to the promotions area.

### CODE REVIEW

**Review by gyasistory — COMMENTED** [review]
Is there a way to test locally this is all I get when I run it locally?

image

**Comment by wrandall22** [comment]
You can test it in staging if you want. The only way to test it locally that I have found so far is to run the API locally as well, which is a bit of a hassle. This is due to the fact that the staging API Okta implementation always redirects you to the staging environment instead of back to your local.

**Comment by TheNoodleMoose** [comment]
There's a way to test locally without the API running locally. It's a bit hacky though. Go through the process of signing in locally and you will then be redirected to the staging site. From here, open the dev console -> Application -> cookies -> cookies for the site. You'll want to find the `crsToken` and copy that. Now go back to localhost and navigate to route `localhost:9000/auth/pasteCrsTokenHere`. You'll now be authenticated locally! Hope this helps!
Screenshot 2022-08-01 140834

**Review by gyasistory — APPROVED** [review]

**Comment by hlbraddock** [comment]
@wrandall22 
Note that this PR will need to be deployed in tandem with https://github.com/CruGlobal/ert-api/pull/994. 
We can manage the deploy of both, if you like.

**Pull request merged**
