### PR TITLE
Revert "Fix Graduation date question and saving questions validation (#842)"

### PR DESCRIPTION
**Pull request by dr-bizz**
This commit causes all event details to an error on a date field when the user ties to save.

This reverts commit 0db31d84fb88f83057af1544067c3fafb22d046b.

### CODE REVIEW

**Comment by wrandall22** [comment]
Hmm, we need to figure out a solution to the timezone issue Caleb was attempting to fix as well.

**Review by wrandall22 — APPROVED** [review]

**Comment by dr-bizz** [comment]
It seems `app/scripts/directives/datepicker.js` is the file which is causing the error

**Comment by wrandall22** [comment]
We should probably boost our automated testing to catch this kind of error in the future.

**Comment by dr-bizz** [comment]
Yes, we need to beef up ERT's tests and Synthetic Tests to ensure mistakes like these are caught.

**Pull request merged**
