### PR TITLE
EVENT-534 - Create predefined dormitory question

### PR DESCRIPTION
**Pull request by wrandall22**
This creates a predefined dormitory question and relies upon back-end changes in https://github.com/CruGlobal/ert-api/pull/732

### CODE REVIEW

**Comment by wrandall22** [comment]
It is to record the dormitory piece of information in the `people` table. Apparently, someone wanted it, or it wouldn't be in the table.  I would guess it would be for reconnecting students to their dorm's Bible studies when they got back to campus.

**Comment by wrandall22** [comment]
My guess is that off campus students would just put "Off Campus" or something. Also, event coordinators can give a custom question title I believe.

**Comment by OzzieOrca** [comment]
Got it. Sounds fine. The case where the user has no dorm seems a little vague but idk what would be better. Maybe the conference admin would set up a question before this and add a rule to conditionally show it.

**Comment by OzzieOrca** [comment]
Just saw your last comment. The admin could put that in the description or something. Cool.

**Pull request merged**
