### PR TITLE
Event 411 - non us staff payments

### PR DESCRIPTION
**Pull request by dsgoers**
Added a third account type for transfer/scholarship payments.  The conferences team wanted a field that can have a longer/shorter number and/or a name and description.  For now, this is OK with them.

### CODE REVIEW

**Comment by adammeyer** [comment]
Looks good :+1:

**Comment by dsgoers** [comment]
Thanks.  I'll let you know when the API branch is ready.

**Comment by dsgoers** [comment]
Can you review this again?  Instead of having an extra field for international numbers we use the original account number and don't do validation in the API.

**Comment by adammeyer** [comment]
Looks good :+1:

**Pull request merged**
