### PR TITLE
Event 436 mandatory answers in checkbox questions

### PR DESCRIPTION
**Pull request by jayakrishnanv**
@hlbraddock , Implemented forced selection of options in Checkbox questions, please test.

### CODE REVIEW

**Comment by hlbraddock** [comment]
@OzzieOrca Can you review? As per https://jira.cru.org/browse/EVENT-436.

**Comment by OzzieOrca** [comment]
@jayakrishnanv Is there any way you can make a PR that just contains the changes for this feature? There are a bunch of commits from a bunch of other PRs that I've reviewed separately. If the code is really dependent on all the other branches, maybe you could send me a branch I can compare this to in github. Looking at all these changes against master is hard. I suppose getting some of the other branches merged first would make this easier...

**Comment by jayakrishnanv** [comment]
@OzzieOrca This task is dependent on EVENT-381 (https://github.com/CruGlobal/conf-registration-web/pull/491) which in turn is dependent on other branches. In fact, almost all the tasks in CRU-17 feature set are tightly coupled. The "Force Selection" check box in this task is displayed only when a check box option is set as Default (EVENT-381). So, we can't have an independent branch for this task.

**Comment by hlbraddock** [comment]
@OzzieOrca @jayakrishnanv If you both feel that certain front end functionality is complete, especially if those front end branches don't require any back end changes (so the front and backend don't have to be released in tandem), we can move forward with merging them into master. This would make reviewing subsequent branches easier. 

Let me know which branches, if any, are ready for production.

**Comment by jayakrishnanv** [comment]
@hlbraddock @OzzieOrca #497 and #494 requires corresponding back-end branches for back-end validation. Others do not have back-end changes. Out of these, #493 and #492 are independent branches and if @OzzieOrca approves, you can merge to master. Other 2 branches #495 and #491 are dependent on #497 and #494. If #497 is approved, we can merge it to other branches and then merge all the branches to #496 . Right now,  #494, #493 and #492 are merged to #496 .

**Comment by jayakrishnanv** [comment]
@hlbraddock @OzzieOrca Please note that the branches #497 and #494 can work correctly even without the related back-end branches deployed, as these back-end branches just provide an additional level of server side validation.

**Comment by hlbraddock** [comment]
That's great @jayakrishnanv. Thanks for the update and dependency information. Be aware that today most Cru staff are going to be unavailable and will respond later this evening or by tomorrow at the latest.

**Comment by hlbraddock** [comment]
@OzzieOrca Would you prefer we merge individual branches to master one at a time? Or, first merge them all to https://github.com/CruGlobal/conf-registration-web/pull/496 and then the one branch to master?

Either way, I'm going to wait for final branch approval from you before proceeding with merge to master (whether individual branches or final Cru 17 branch). If you would state in your approval comment "ready to merge to master", there will be no confusion.

The only caveat being whenever the backend contains required changes as well. However, I'm understanding from @jayakrishnanv that the only backend changes done (thus far) have to do with validation, which is therefore not tightly coupled to front end release.

**Comment by OzzieOrca** [comment]
I like the idea of merging them individually.

**Comment by jayakrishnanv** [comment]
@hlbraddock @jcsaplar @OzzieOrca Please use #501  instead of this.

**Comment by jayakrishnanv** [comment]
@hlbraddock @OzzieOrca @jcsaplar Since you have decided to merge branches individually to master, we have created fresh branches #500 and #501 which contain changes specific to these tasks.. Please test and merge these branches instead of the old ones.

 If you can test and approve all the branches today, we can merge them to CRU-17 branch (will create a fresh branch, as the current one has lots of unwanted commits) and test from our side. 

Current active branches to test and merge to master:

#492 
#493 
#494 
#499 
#500 
#501

**Comment by hlbraddock** [comment]
@jayakrishnanv @OzzieOrca Please delete any branches that are no longer relevant. For instance, we have the following branches for EVENT-379:

https://github.com/CruGlobal/conf-registration-web/tree/EVENT-379-Scotty's-Version
https://github.com/CruGlobal/conf-registration-web/tree/EVENT-379-Valid-option-range-for-number-questions
https://github.com/CruGlobal/conf-registration-web/tree/EVENT-379

**Pull request closed without merging**
