### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by JasonBuckner**
adjust copyright year to current

### CODE REVIEW

**Comment by MeatpieNov** [comment]
Resolves https://secure.helpscout.net/conversation/170220690/36752/?folderId=320675

**Comment by ryancarlson** [comment]
Why not create a small service that just grabs the year from the current date?  That way we don't have to update it every year :)

**Comment by JasonBuckner** [comment]
Well, the one I have the most experience with is `<?php echo date("Y") ?>`, but that's not really an option here.

**Comment by ryancarlson** [comment]
@JasonBuckner we like to have someone give an approval to the PR before it gets merged.  this one's trivial, so not a big deal, but in the future you should wait for a 👍  or "Looks good to me" before merging.

**Comment by JasonBuckner** [comment]
Understood. Thanks for the heads up on protocol @ryancarlson .

**Comment by dougworner** [comment]
Why not just copy/paste in JavaScript?

<script language="javascript" type="text/javascript">
     var today = new Date()
     var year = today.getFullYear()
     document.write(year)
</script>

**Comment by JasonBuckner** [comment]
Care to make a Pull request for that @dougworner ?

**Pull request merged**
