### PR TITLE
EVENT-660-new Blurb for International Currency Selection

### PR DESCRIPTION
**Pull request by caleballdrin**
https://jira.cru.org/browse/EVENT-660
Screen Shot 2020-03-11 at 2 54 21 PM

### CODE REVIEW

**Comment by caleballdrin** [comment]
Here is what I did to reset my local files since I merged them with staging:
git fetch --all
git reset --hard origin/master

Hopefully that reset everything to master and then I created a new branch, made changes, committed changes, ran it locally, then pushed up the new branch.

**Comment by wrandall22** [comment]
Code and commit look pretty good. Can you mention in the Jira ticket that it is in staging for QA testing? I'm not 100% sure on the process for ERT specifically when it comes to QA. Either @TheNoodleMoose or @hlbraddock should know the process. Also, please update the status of the Jira ticket.

**Comment by caleballdrin** [comment]
Ok I just updated the Jira ticket. I assume that I should push it up so that the change is actually in staging?

**Comment by wrandall22** [comment]
The change is in staging, and has been for a couple days, when we merged it to staging in #686

**Comment by caleballdrin** [comment]
Ok for some reason it isn't showing up for me when i go to the staging.evenregistrationtool.com site. Is it there for you?

**Comment by wrandall22** [comment]
It was on https://stage.eventregistrationtool.com/ the other day, but seems to have gone away.

**Comment by caleballdrin** [comment]
Ok, I just merged master into staging and then merged EVENT-660-new into staging and pushed it up.

**Comment by caleballdrin** [comment]
Let me know how long I should wait for QA testing and what I should do next.

**Comment by wrandall22** [comment]
@caleballdrin go ahead and merge and then update the Jira ticket to be deployed.

**Pull request merged**
