### PR TITLE
EVENT-660 - Blurb for International Currency Selection 

### PR DESCRIPTION
**Pull request by caleballdrin**
New pull request.

https://jira.cru.org/browse/EVENT-660

Screen Shot 2020-03-11 at 11 05 12 AM

### CODE REVIEW

**Comment by wrandall22** [comment]
Did you try running this locally as is mentioned in the README?

**Comment by caleballdrin** [comment]
> Did you try running this locally as is mentioned in the README?

Yes! I was able to install yarn and I setup VScode to format to prettier onsave. I ran it on my computer and it worked so I pushed it from terminal and then created a pull request. Should I have done a pull request with master or with staging?

**Comment by wrandall22** [comment]
Can you post a screenshot of it working here in the PR comments or description?

As far as flow goes, once you are used to a project typically you would pull the latest staging down to your local and merge your changes to staging there, and push staging up. Then you would make a PR against master. However, since you are new to the project and the flows we do here, it makes sense for you to make a PR against staging, then later a separate PR from your branch to master.

The commit history you have going here is a bit messy, but we can work with getting that nicer over time.

**Comment by caleballdrin** [comment]
Ok I just added a screenshot to the description. 
In the future I will make a branch off staging, then merge them and push staging up.

What should I do now?

**Comment by wrandall22** [comment]
Now that I've approved the pull request, you can merge it.

**Comment by wrandall22** [comment]
For the flow, ideally you would branch from master, then make sure your local has the latest staging changes from GitHub. If staging doesn't have master in it, merge the latest master branch into staging and push it up to staging. In this case, you shouldn't have to merge staging into your feature branch, and shouldn't have any weird commits going from your feature branch into staging.

**Comment by wrandall22** [comment]
Now you should be able to test your same change in [Stage](https://stage.eventregistrationtool.com/)

**Comment by caleballdrin** [comment]
Ok, that makes sense to branch from master.

**Comment by caleballdrin** [comment]
Looks like its working! I assume it's okay to create new events on the Stage site to test things?
Should I make a pull request to Master now?

**Comment by wrandall22** [comment]
Yes and yes

**Pull request merged**
