### PR TITLE
EVENT-660 Blurb for International Currency Selection

### PR DESCRIPTION
**Pull request by caleballdrin**
https://jira.cru.org/browse/EVENT-660
Screen Shot 2020-03-11 at 11 05 12 AM

### CODE REVIEW

**Comment by wrandall22** [comment]
So, this is a bit problematic since you merged the staging branch into your feature branch.

**Comment by caleballdrin** [comment]
yeah... so I will probably need redo things and make a new branch off master. make my changes and then push up the new branch?

**Comment by wrandall22** [comment]
That would probably be the easiest thing in this particular case.

**Comment by wrandall22** [comment]
I'll post a couple of other options that are a bit more advanced, but result in less rework when you have more commits.

**Comment by wrandall22** [comment]
You can use [Git cherry-pick](https://git-scm.com/docs/git-cherry-pick) to not have to redo the work as well.

**Comment by wrandall22** [comment]
There also appears to be quite a few lint errors in the master branch cc @TheNoodleMoose

**Comment by caleballdrin** [comment]
I have to head out right now but I will finish it up later this afternoon.

**Comment by TheNoodleMoose** [comment]
@wrandall22 what lint issues are you seeing? The build for master seems to be fine https://travis-ci.org/github/CruGlobal/conf-registration-web/branches. Did you get these when you ran `yarn lint`? We don't check for that during the build but maybe we should...

**Comment by wrandall22** [comment]
Correct, it doesn't appear to be running during the Travis build.

**Comment by wrandall22** [comment]
Another option ([Rebase](https://git-scm.com/docs/git-rebase)):
- `git rebase -i head~4 --preserve-merge`
- Delete the top 2 lines which talk about merging staging into your branch
- Save and quit
- [Force push](https://git-scm.com/docs/git-push#Documentation/git-push.txt--f) the branch: `git push origin EVENT-660 -f`

**Comment by wrandall22** [comment]
Replaced by #690

**Pull request closed without merging**
