### PR TITLE
EVENT-778-Provide-Filtering-On-Registrations-Export

### PR DESCRIPTION
**Pull request by TheNoodleMoose**
Ticket: https://jira.cru.org/browse/EVENT-778

The main purpose of the ticket was to add a new checkbox in the advanced options menu to apply current registration filters to the registration export. But I saw the opportunity to convert to react, so I went ahead and did that too 🙂

### CODE REVIEW

**Comment by wrandall22** [comment]
Git history may have been nicer if it was 2 commits: 1 to add the checkbox, and 1 to convert to React.

**Comment by TheNoodleMoose** [comment]
@wrandall22 That's a great point. @aaronlaib This is an example where although what I did in the commit connects with the work needed to be done, splitting it into two commits would help with clarity. I'll go about splitting this(1st commit converting to react; 2nd commit adding relevant checkbox).

**Review by OzzieOrca — APPROVED** [review]

**Comment by TheNoodleMoose** [comment]
@wrandall22 Went ahead and split the commits, thanks for the suggestion! This will need to wait to go to staging/production until the related API work is live.

**Comment by TheNoodleMoose** [comment]
@wrandall22 Scotty had approved this before, it just needs reapproval.

**Review by wrandall22 — APPROVED** [review]

**Pull request merged**
