### PR TITLE
Login dialog fixes

### PR DESCRIPTION
**Pull request by adammeyer**

### CODE REVIEW

**Comment by adammeyer** [comment]
@ryancarlson or @OzzieOrca can you do a review when you have a sec. thanks!

**Comment by ryancarlson** [comment]
I can, but @OzzieOrca since you guys talked about this one, do you want to do the review?

**Comment by OzzieOrca** [comment]
I glanced through the code. I can't quite remember the conversation. I might be able to look at it tonight but I'm going to be driving all day.

**Comment by ryancarlson** [comment]
No worries then, I'll look at it here in a second.

**Comment by adammeyer** [comment]
Thanks @OzzieOrca.  This one is not regarding a conversation we had.  Just some updates to the login modal that won't ruin how the page behind it looks with the new landing page.

**Comment by ryancarlson** [comment]
@adammeyer so the gist here is that the login options window now has a close (x)?  the other smaller things are fine.  this looks goood.

**Comment by adammeyer** [comment]
@ryancarlson Yes, and also doesn't remove the header/footer of the landing page when it is opened.

That's these lines: https://github.com/CruGlobal/conf-registration-web/pull/318/files#diff-90a034613d1a338a0ecb898a6cb43e88L4

**Comment by ryancarlson** [comment]
Nice.. looks good

**Pull request merged**
