### PR TITLE
Registrant check-in, check-in and withdrawn filter

### PR DESCRIPTION
**Pull request by adammeyer**

### CODE REVIEW

**Comment by adammeyer** [comment]
@OzzieOrca Can you review?
I know this might create some more merge headaches for your responsive branch... sorry! :)

**Comment by adammeyer** [comment]
We can think of a better way to display the filters. This was just my best first attempt.

**Comment by hlbraddock** [comment]
+1

**Comment by hlbraddock** [comment]
Shouldn't PR title read `Registrant incomplete, check-in and withdrawn filter`

**Comment by hlbraddock** [comment]
Could the `incomplete` registrations filter be renamed `complete registrations`? The filter function could then be reduced to one shared function.

**Pull request merged**
